apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: goappofapps-gitops
  description: This is GitOps manifest for goappofapps   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: goappofapps
    janus-idp.io/tekton: goappofapps 
    backstage.io/kubernetes-id: goappofapps
    backstage.io/kubernetes-namespace: goappofapps
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:goappofapps
