apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: goappofapps
  janus-idp.io/tekton: goappofapps
  backstage.io/kubernetes-id: goappofapps
  backstage.io/kubernetes-namespace: goappofapps 
  app.kubernetes.io/part-of: goappofapps
resources: 
- deployment.yaml
- route.yaml
- service.yaml
