apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: goappofapps
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: goappofapps 
  name: goappofapps
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: goappofapps
    weight: 100 
